### ISSUE TITLE
Bug: cannot distribute volume of numbers to texters and save 

### ISSUE THREAD

**Issue by markyv18** [StateVoicesNational/Spoke#2045]
**Describe the bug**

**To Reproduce**
I go into a campaign, i click edit, i open the 'texters' tab, i redistribute the volume of texts and attempt to save...  Refresh page and nothing is saved. 

**Expected behavior**
I expect the values to save 

**Screenshots**
see attached 

**Platform (please complete the following information):**
 - OS: 11.2.1 (M1 chip) 
 - chrome & safari
 - Desktop or Mobile?  Both
 - 11.0 

<img width="675" alt="Screen Shot 2021-09-20 at 8 58 16 PM" src="https://user-images.githubusercontent.com/17706958/134105765-4c60460e-42fb-47c8-82d3-a933205541f3.png">
<img width="651" alt="Screen Shot 2021-09-20 at 8 58 35 PM" src="https://user-images.githubusercontent.com/17706958/134105771-1f928d61-fb49-4d61-b6ab-c84963304366.png">
**Additional context**

**Comment by markyv18** [comment]
I deployed this app on an M1 chip computer, wondering if that somehow screws up the build

**Comment by schuyler1d** [comment]
Not related to M1 :-)  If you have an environment to test, would like feedback on this PR for the fix:
https://github.com/MoveOnOrg/Spoke/pull/2041
