### ISSUE TITLE
"Unarchive" instead of "Archive"

### ISSUE THREAD

**Issue by Arique1104** [StateVoicesNational/Spoke#2056]
**Notes**
Search for campaign is archive menu by Spoke campaign ID and date created
**Describe the bug**
In the Archives page
Change it to say "unarchive" instead of "archive"

**To Reproduce**
1. Go to 'Campaigns'
<img width="651" alt="Screen Shot 2021-10-07 at 5 13 37 PM" src="https://user-images.githubusercontent.com/60521756/136474686-45cf025c-8083-4848-92b2-d904ff84c185.png">

1.1 If you don't have any campaigns, create one.

2. Click on a campaign
<img width="658" alt="Screen Shot 2021-10-07 at 5 16 50 PM" src="https://user-images.githubusercontent.com/60521756/136474909-c471883e-1959-4eea-ae99-959db1a2e6f3.png">

3. Change the "Archive" button to "Unarchive"
<img width="954" alt="Screen Shot 2021-10-07 at 5 17 48 PM" src="https://user-images.githubusercontent.com/60521756/136475091-4aed8f0d-66b1-4220-8785-6933e942ccc0.png">

**Platform (please complete the following information):**

**Additional context**
N/A

**Comment by holdengreen** [comment]
Is this still an issue?

**Comment by crayolakat** [comment]
Issue has been fixed in Spoke version 11.1
