### ISSUE TITLE
Bug: text messages truncated for some recipients

### ISSUE THREAD

**Issue by lrperlmu** [StateVoicesNational/Spoke#2058]
**Describe who you are**
I am a text message recipient recieving text messages from my favorite political campaign via spoke. (I know it's spoke because when I noticed this bug I asked which platform they were using.)

**Describe the bug**
Every time I receive a message longer than 140 characters, I only receive the first 140 characters of the message.

I texted back, and told the organizer that text messages are truncated for me, and they said that they know this is happening for spoke messages sent to a small number of their recipients and they have no idea how to fix it. They said that most recipients in this campaign receive longer messages as multiple texts.

**To Reproduce**
Unknown -- I'm not the one sending the text messages.

**Expected behavior**
Messages longer than 140 characters will be received as multiple texts.

**Screenshots**

**Platform (please complete the following information):**
Android Messages app on 2016 Pixel phone

**Additional context**
Is it possible that the problem is on my end as the recipient? (I have an older phone.) Are there any phone settings that I can toggle in order to make my phone receive the messages properly?

**Comment by mau11** [comment]
Thanks @lrperlmu, we're reviewing outstanding issues. Messages longer than this character limit must be sent by MMS as SMS has a character limit. If you notice any other issues, please create a new one.
