### ISSUE TITLE
Bug: Heroku One-Click Set Up w/ VAN Default Variables Pausing Usability

### ISSUE THREAD

**Issue by Arique1104** [StateVoicesNational/Spoke#2072]
**Describe the bug**
In order to set up a Spoke Instance through Heroku, there are a set of global variables - particularly for the VAN that are set to be required but aren't actually required to begin utilizing Spoke.

**To Reproduce**
1. Go to 'Heroku One-Click Setup on ReadMe'
2. Click on Heroku One-Click Setup'
3. Try to begin using Spoke without a DEFAULT_GLOBAL_VAN value

**Expected behavior**
This ticket is two fold.  We would still like to maintain any streamlining of VAN Integration usage, ensuring that whoever needs the VAN Integration, they still have a user-friendly experience doing so.

Also we would like to "turn off" these required settings when a VAN Integration is not a priority for our Spoke User.  Ensuring that their campaign can move forward without having to do any heavy customizing of the codebase.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Desktop

**Additional context**
This bug was brought to our attention by our partner organization StateVoices and is high priority because it caused a lot of confusion during this recent election cycle. Must have bug fixed before end of January 2022, if not sooner.

**Comment by schuyler1d** [comment]
I would recommend creating a new service-manager which implements getOrganizationData and onOrganizationUpdateSignal and react-component.js functions, which creates/adds an interface to enter VAN environment variables through the UI (and also enables the other extensions in/for the organization -- maybe allowing them to enable/disable different pieces -- and also maybe auto-creating tags to make sure those features can fully work).

**Comment by arena** [comment]
Related to this is the way the heroku button---actually two buttons---is presented in the readme
https://github.com/MoveOnOrg/Spoke/issues/2105

**Comment by Arique1104** [comment]
@WMudgeEllis, @n0land0, @Samantha-Brown 

After touching base with @ibrand, I wanted to encourage you to think about if the VAN environment variables could live under the Service Management panel within the Campaign creation form.

We'll want to hide this configuration for orgs that don't want to have this service turned on.

**Comment by schuyler1d** [comment]
This relates to work @stefanhayden was working on recently.
