### ISSUE TITLE
Removing Retired Phone Numbers (Twilio)

### ISSUE THREAD

**Issue by Arique1104** [StateVoicesNational/Spoke#2074]
Figure out how to remove old numbers from Twilio that are no long in service but still appears within Spoke (possible API update.)

**Comment by schuyler1d** [comment]
I would recommend implementing this with a new service-manager with an onDeliveryReport hook:
https://github.com/MoveOnOrg/Spoke/blob/main/src/extensions/service-managers/test-fake-example/index.js#L25-L38
and then adding/updating entries with the relevant error codes to the `organization_contact` table similar to this service manager:
https://github.com/MoveOnOrg/Spoke/blob/main/src/extensions/service-managers/scrub-bad-mobilenums/index.js#L183
I would be careful about error codes -- e.g. 'out of service' numbers disproportionately affect poorer folks and are sometimes temporary -- maybe the service manager's configuration (react-component.js and getOrganizationData and onOrganizationUpdateSignal) could give some options to enable/disable some of them (that would be extra-credit -- just making it a service-manager means it can be added/removed at least at the instance level).
Any error codes you leverage, please also add them here:
https://github.com/MoveOnOrg/Spoke/blob/main/src/extensions/service-vendors/twilio/index.js#L82

**Comment by Arique1104** [comment]
@schuyler1d, this is specifically for purchased 10DLC numbers from Twilio.  We're not touching people data, we're trying to create a new to old chronological order for purchased numbers from Twilio.

Would you still suggest that we go the Service Manager route?  Because I believed this was a new SQL query to be implemented on the front end for the drop-down UI for administrators of Spoke assigning 10DLC numbers to the different orgs/volunteers and not having to scroll all the way to the end of that dropdown to find their new purchased numbers.

I still don't have a clear idea of what the logic would be for removing old numbers (purchased from TWILIO) that are no longer in use.  But as a first over, I believe that new to old ordering of these numbers would reduce some pain points for larger organizations who purchase Twilio for other orgs.

**Comment by schuyler1d** [comment]
Ah, disregard what I said above -- I thought it was referring to out-of-service contact numbers.

Maybe instead, make the numbers table sortable, both by number and by acquisition date.
I think there's already a delete (maybe I'm wrong) -- maybe it broke?  Or this is for bulk-removal?

**Comment by Arique1104** [comment]
Before pairing with @n0land0, I wasn't considering destroying anything.  I believe that requires more input from our organizations, it depends on how they manage their purchased Twilio numbers.

I like your concept of making the numbers table sortable.  That'll give our users more flexibility.

@crayolakat had suggested not tampering with the table that holds this information on the backend, but rather locating where it appears in the frontend and once we find that, altering the presentation of the data from newest to oldest.  I think once we figure that out, we can add more sorting settings to the front end.

I'll post the table information in a bit.

**Comment by n0land0** [comment]
- Routes: `/src/routes.jsx` - since components will not render on the `/admin/12/phone-numbers` path with our particular admin privileges, we traced the component that should be rendered
- Primary File: `/src/containers/AdminPhoneNumberInventory.js` - identified operations to buy and delete phone numbers
- Secondary File: `/src/containers/hoc/load-data.jsx` - getting a sense of what role the `loadData` wrapper plays, since `AdminPhoneNumberInventory.js` is exported with it
- Permissions: `/src/components/AdminDashboard.jsx`:  we need to figure out if superadmin, admin, supervolunteer get the same privileges for our addition

@schuyler1d Are we on the right track?

**Comment by Arique1104** [comment]
We have begun looking into where in the code we would add the fix.

In the `AdminPhoneNumberInventory.js`

We've identified that on lines 343-368 there is a function to sort the order by name and direction.

```javacript
    const options = {
      filterType: "checkbox",
      selectableRows: this.props.selectMultiple ? "multiple" : "none",
      elevation: 0,
      download: false,
      print: false,
      searchable: false,
      filter: false,
      sort: true,
      search: false,
      viewColumns: false,
      page: 1,
      serverSide: true,
      onTableChange: (action, tableState) => {
        switch (action) {
          case "sort":
            handleSortOrderChange(
              tableState.sortOrder.name,
              tableState.sortOrder.direction
            );
            break;
          default:
            break;
        }
      }
    };
```

Due to authorization we do not have access to a live account where we can interpret in the console what our changes would be, but are beginning to suspect that this is the function we were looking to build.

Need more time to figure if the function we are setting out to create is already represented here.

Next Steps:
- Get access to a live Spoke app with admins access to purchasing phone numbers.
- See where this code that already exists function.
- Decide from there to consider this issue resolved.

**Comment by Arique1104** [comment]
We have decided that this issue is resolved.  As we continue updates for the Admin Dashboard, it would be a strong case to make sure that there is proper documentation update so that more Admin Users can understand the opportunities they have to manage their purchased Twilio phone numbers per campaign.
