### ISSUE TITLE
Bug: Outbound Unassign doesn't work unless Redis is set up in your dev environment

### ISSUE THREAD

**Issue by crayolakat** [StateVoicesNational/Spoke#2077]
**Describe the bug**
If Redis isn't set up in your dev environment, outbound unassign won't work.

**To Reproduce**
1. Make sure there isn't a `REDIS_URL` entry in the `.env` file
2. Start your dev environment
3. Create a campaign. In the `Texter Experience` panel, enable the `Take Conversations` toggle. Enable the `Enable initial outbound unassign` toggle. Include the `autorespond` keyword in your `Interaction` script
4. Fill in all other mandatory parts of the campaign and start it.
5. Assign a texter to the campaign
6. Log in as the texter and send some initial messages
7. Issue: Conversations are not unassigned from you after you send the initial messages.

**Expected behavior**
Conversations should be unassigned from you after you send the initial messages.

**Platform:**
 - OS: macOS
 - Browser: Chrome
 - Desktop
 - Version: 95.0.4638.69
 
 Issue will happen on any browser

**Additional context**
https://github.com/MoveOnOrg/Spoke/blob/06f743fff9d9764a5f900ee561eccda9ecd82dc2/src/extensions/message-handlers/outbound-unassign/index.js#L23-L48

The above block of code is the issue. The `r.redis` in the outer if condition should be moved inside, and only encapsulate lines 37-42.

**Comment by holdengreen** [comment]
Hey sorry for taking so long to do this...

I created a pull with the code I remember being required, but there should still likely be work to do.
