### ISSUE TITLE
Bug: regexp error parsing custom contact fields

### ISSUE THREAD

**Issue by inorvig** [StateVoicesNational/Spoke#2087]
**Describe the bug**
Some custom fields/column titles in contact CSVs are not parsed

**To Reproduce**
1. Upload contact csv with custom fields
2. Join campaign
3. Click "Start texting"
4. Screen is blank, inspect console for error

**Expected behavior**
Expect an error when CSV is uploaded (or for the field to be parsed correctly)

**Screenshots and examples**
Example A:
![Screenshot 2021-11-29 4 57 57 PM](https://user-images.githubusercontent.com/3752857/144279246-f928067d-4e7a-47c0-a249-a0a96e9a1d58.png)
Error in example A was `SyntaxError: Invalid regular expression: /{0}/: Nothing to repeat`

Example B:
`SyntaxError: Invalid regular expression: /{question[Vote-Early voting?]}/: Range out of order in character class at new RegExp (<anonymous>)`
There was a column called question[Voter-Contact voting?] in the list of contacts uploaded to that campaign

**Platform (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome
 - Desktop or Mobile? Desktop
 - Version 11.1

**Comment by lperson** [comment]
The regex engine is interpretting the square brackets as [defining a range](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges), not literal square brackets. It expects characters in a range to be in order. If you want square brackets to be interpretted literally, escape them by adding a backslash before them, e.g.,

```
/{question\[Vote-Early voting?\]}/
```
