### ISSUE TITLE
Bug: Unable to change Auth0 Email

### ISSUE THREAD

**Issue by crayolakat** [StateVoicesNational/Spoke#2155]
**Describe the bug**
When the user changes their email in their Spoke profile settings, it won't be updated in Auth0 if the Auth0 passport strategy is enabled. The user would still have to log into Spoke using their old email address, and won't be able to use the "Don't remember your password" link if they forgot their password. Currently, only admins who have access to Auth0 can update a user's email. It would be better if when someone updates their own email in their Spoke profile settings, this update is also reflected in Auth0 and their login credentials.

**To Reproduce**
1. Log in as a user via Auth0
2. Go to the user profile page and change your email
3. Log out
4. Issue 1: If the user tries logging in again they must log in using their old email and password. The new email isn't updated in Auth0
5. Issue 2: If the user clicks "Don't remember your password" at the login screen, a reset password email will be sent to the old email instead of the new email. This doesn't help in the case when someone changed their Spoke email because they lost access to their old email

**Expected behavior**
When the user changes their email in their Spoke profile settings, it should also be updated in Auth0.

**Screenshots**
User profile page
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9382984/162593537-89947701-1694-4a65-8c7b-19b0b496b94a.png">

Auth0 login screen
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9382984/162593512-1ced9d0a-32c5-4fd7-9b21-88cbb4178467.png">

**Comment by crayolakat** [comment]
Notes from @codygordon :

Allowing Auth0 users to change their emails is somewhat complicated and requires using the [Management API](https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id), and we'd probably want to validate the email is owned by the user by verifying it via auth0 OTP before the change is accepted.

Maybe we should just disable editing the email for auth0 users in the meantime, since it doesn't actually work?

**Comment by MoveQA** [comment]
@codygordon I reviewed this bug with  Arique last week and we agree that removing the 'chance password' is the most reasonable solution at this time.

**Comment by crayolakat** [comment]
This fix for this was merged into the `main` branch for the 12.2 release, but some rebasing caused the issue to not close automatically. Manually closing this issue.
