### ISSUE TITLE
Feature Request: Configure 1-click initial outbound message sending by batch and campaign

### ISSUE THREAD

**Issue by ErikKirkstein** [StateVoicesNational/Spoke#2161]
**Problem**
Currently, All MoveOn instances of Spoke allow for one-send-per-click and keyboard-based button compression to send all outbound messages in a batch or campaign. 

**Solution**
Configure Spoke to allow all initial outbound text messages per batch (or campaign) to be sent with 1 single click of the send button.

**Context**
Ideally, this setup would function with a specific toggleable button within a Spoke campaign that can be turned on our off by a user with admin level access.

**Comment by crayolakat** [comment]
We already have a feature called "Bulk Send" which allows this.

Currently, the [documentation](https://moveonorg.github.io/Spoke/#/HOWTO-use_bulk_sending_outside_the_USA?id=about-bulk-sending) says that it’s illegal to bulk send in the USA and the code actually prevents bulk sending unless `NOT_IN_USA=true` is specified in the .env file. However, this is no longer true.

Next steps for this Feature Request is to remove the NOT_IN_USA=true restriction for bulk sending and update the documentation
