### ISSUE TITLE
Bug: Strings enclosed in <> in the documentation aren't displaying on the Documentation Microsite

### ISSUE THREAD

**Issue by crayolakat** [StateVoicesNational/Spoke#2164]
**Describe the bug**
Any string enclosed in <> in the documentation doesn't display on the Documentation Microsite unless it's also enclosed in backticks

**To Reproduce**
1. Observe the `<YOUR_APP_URL>` string in the following line: https://github.com/MoveOnOrg/Spoke/blob/ce5d1290a5c4ef3ea0a7d105dc839a1917545df1/docs/HOWTO_INTEGRATE_TWILIO.md?plain=1#L9
2. Go to https://moveonorg.github.io/Spoke/#/HOWTO_INTEGRATE_TWILIO
3. **Issue:** The `<YOUR_APP_URL>` string isn't displaying

**Expected behavior**
The `<YOUR_APP_URL>` string should display

**Screenshots**
<img width="1439" alt="Screen Shot 2022-05-07 at 10 44 42 AM" src="https://user-images.githubusercontent.com/9382984/167265839-4bba2b70-3b78-4463-a26b-5def921f450c.png">

**Additional context**
Possible solution: Enclose all strings in the documentation enclosed in <> with backticks

**Comment by AlexOde** [comment]
Hey! I'd like to take a look at this one, if that would be ok?

**Comment by crayolakat** [comment]
Fixed via this PR https://github.com/MoveOnOrg/Spoke/pull/2166
