### ISSUE TITLE
Bug: Campaign Settings Changes not sticking after contacts upload

### ISSUE THREAD

**Issue by ryanjcrump** [StateVoicesNational/Spoke#2175]
**Describe the bug**
When changing settings in Dynamic Assignment and Texter Experience (maybe more!), these settings do not stick after uploading a list an scrubbing landlines. 

**To Reproduce**
I updated Dynamic Assignment and Texter Experience settings, then uploaded a list and scrubbed landlines and the settings had reverted to default.

**Expected behavior**
Changing settings on the campaign level should stick forever until manually changed.

**Platform (please complete the following information):**
iOS, chrome, desktop, latest version

**Comment by engelhartrueben** [comment]
Please re-open if this issue persists.
Thanks for helping Spoke become a better platform!
