### ISSUE TITLE
Bug: Export Stuck

### ISSUE THREAD

**Issue by andrewlearned** [StateVoicesNational/Spoke#2183]
**Describe the bug**
I've exported before with no issues, but one export of mine is stuck at 0%, the button becomes inoperable and there doesn't seem to be any way to "force" a reset or anything. It's been like this for days now. I've tried restarting the dynos but nothing is working.

**To Reproduce**
1. No idea. Besides being a larger than normal export (about 70k records) nothing was abnormal but since the button is no longer clickable (says "Exporting 0%) I cant recreate it.

**Expected behavior**
A export link appears in the browser after I refresh the page. Didn't happen this time.

**Screenshots**
None available.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, but I've tried other browsers and it doesn't help
 - Desktop or Mobile: Desktop
 - Version not sure, I installed from here about 2 months ago though

**Additional context**

**Comment by joemcl** [comment]
Try running in sql - DELETE FROM job_request

**Comment by joemcl** [comment]
Also @schuyler1d any thoughts on the cause of this?

**Comment by joemcl** [comment]
Also @andrewlearned please apply to join the Progcode Slack channel for Spoke, see
https://github.com/MoveOnOrg/Spoke/blob/main/CONTRIBUTING.md

**Comment by andrewlearned** [comment]
on it!


<http://andrewlearned.com/>
Rep. Andrew Learned
Florida House District 59
[image: T]  813.856.1212  <813.856.1212>[image: M]  ***@***.***
  805 E. Bloomingdale Ave #390 Brandon, FL 33511
     <https://facebook.com/andrewlearned>
<https://twitter.com/AndrewLearned>  <http://instagram.com/Andrew_Learned/>
<https://twitter.com/AndrewLearned>
AndrewLearned.com <http://andrewlearned.com/>

**Comment by schuyler1d** [comment]
this should be the default, but make sure you're running with the environment variable JOBS_SAME_PROCESS=1
Are you on Heroku or hosting elsewhere?

**Comment by andrewlearned** [comment]
Heroku. It's just the one export. I can't recreate it because now the
button is unclickable.

Jobs_Same_Process=1, confirmed.

Thanks for your help on this! Attaching a screenshot. Everything should be
pretty standard, I followed your github instructions.

[image: sdfasdpture.PNG]

-Andrew



<http://andrewlearned.com/>
Rep. Andrew Learned
Florida House District 59->69
[image: T]  813.856.1212  <813.856.1212>[image: M]  ***@***.***
  805 E. Bloomingdale Ave #390 Brandon, FL 33511
     <https://facebook.com/andrewlearned>
<https://twitter.com/AndrewLearned>  <http://instagram.com/Andrew_Learned/>
<https://twitter.com/AndrewLearned>
AndrewLearned.com <http://andrewlearned.com/>

**Comment by schuyler1d** [comment]
Yeah to make it clicked again run Joe's command
https://github.com/MoveOnOrg/Spoke/issues/2183#issuecomment-1152581699
And restart your redis server

**Comment by andrewlearned** [comment]
If it's not too much, can you explain that a bit more? I'm learning this on
the fly!

**Comment by joemcl** [comment]
SQL is a query language used by relational databases. See here - https://www.w3schools.com/sql/default.asp 

Spoke uses the Postgresql database to store data and that uses a particular 'flavor' of SQL - 
see here - 
 https://www.postgresql.org/about 

What I posted above is a SQL command that should clear the stuck data export query and let you attempt to run that again

You can use 'dataclips' in Heroku to run SQL commands - see here - 
https://devcenter.heroku.com/articles/dataclips

**Comment by andrewlearned** [comment]
Hey Joe, separate issue. Any idea what the error:  "First Message Sent
error: -1", means? Here's the screenshot:

[image: Capture.PNG]

I was testing sending an MMS but the request never made it to Twilio logs.

-Andrew

<http://andrewlearned.com/>
Rep. Andrew Learned
Florida House District 59->69
[image: T]  813.856.1212  <813.856.1212>[image: M]  ***@***.***
  805 E. Bloomingdale Ave #390 Brandon, FL 33511
     <https://facebook.com/andrewlearned>
<https://twitter.com/AndrewLearned>  <http://instagram.com/Andrew_Learned/>
<https://twitter.com/AndrewLearned>
AndrewLearned.com <http://andrewlearned.com/>

**Comment by crayolakat** [comment]
Hey Andrew, I've seen that error before when Twilio configuration isn't properly set up. Question: Are you able to successfully send an SMS or do you get the same error?

**Comment by andrewlearned** [comment]
Yeah, sms is working fine. I was mainly checking the config, is it just
[URL]? Maybe I got that part wrong and that's throwing it?

<http://andrewlearned.com/>
Rep. Andrew Learned
Florida House District 59->69
[image: T]  813.856.1212  <813.856.1212>[image: M]  ***@***.***
  805 E. Bloomingdale Ave #390 Brandon, FL 33511
     <https://facebook.com/andrewlearned>
<https://twitter.com/AndrewLearned>  <http://instagram.com/Andrew_Learned/>
<https://twitter.com/AndrewLearned>
AndrewLearned.com <http://andrewlearned.com/>

**Comment by crayolakat** [comment]
@andrewlearned Can you provide a screenshot of the MMS script that you're trying to send? Here is an example:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9382984/180283335-522762a4-965b-41f2-b569-4e32f644fa24.png">

**Comment by andrewlearned** [comment]
Hey Kathy, sorry for the delay. Yeah, SMS is working fine. It's just the
images I'm having trouble with.

<http://andrewlearned.com/>
Rep. Andrew Learned
Florida House District 59->69
[image: T]  813.856.1212  <813.856.1212>[image: M]  ***@***.***
  805 E. Bloomingdale Ave #390 Brandon, FL 33511
     <https://facebook.com/andrewlearned>
<https://twitter.com/AndrewLearned>  <http://instagram.com/Andrew_Learned/>
<https://twitter.com/AndrewLearned>
AndrewLearned.com <http://andrewlearned.com/>

**Comment by crayolakat** [comment]
@andrewlearned What's the MMS image link that you're trying to use in the Spoke script? Also, if you want to schedule a meeting with me to help troubleshoot, send me an email at kathy.nguyen@moveon.org

**Comment by andrewlearned** [comment]
Sorry for my delay! Totally missed this, got everything working great now. THank you.
