### ISSUE TITLE
Bug: CSV Export & VAN Integration

### ISSUE THREAD

**Issue by Arique1104** [StateVoicesNational/Spoke#2223]
Walk through CSV export data

**Describe the bug**

**To Reproduce**
1. Go to create a New Campaign
2. Load up contacts
3. Load the list, with these fields:  firstname, lastname, cell, external_id === van_id, dwid, zip
4. The software recognizes one customfield
5. Hits save and nothing happens
6. No error and nothing in the info box

IN INFO LOGS

- It tells you what the processing chunk is and a json object that tells you how many things got loaded.  
- It doesn’t show any errors on the front or backend.

**Expected behavior**
We expect to be able to upload all people with their custom fields so that the synching between The VAN and Spoke is behaving as we expect it to.  Being able to mark and update the contact across campaigns, their responses, etc.

**Additional context**
This is a very difficult data bottle neck and will impact scaling capacities moving into GOTV.

**Comment by mabrownnyu** [comment]
@Arique1104 We were able to resolve this by updating our Spoke to the most recent version.
