### ISSUE TITLE
Bug: LocalHost URL overwriting Twilio CallBack URL

### ISSUE THREAD

**Issue by Arique1104** [StateVoicesNational/Spoke#2224]
**Describe the bug**

- Error Messages from Twilio (report back on the specific numbers)
- Global variables versus Organization variables
- When you save the Twilio keys and when you put in the Twilio Callback…kept the default values on the environment variable, considering they might be overwritten due to the integration.
- The callback URL defaults to a LocalHost URL
- In certain instances, it tries to send the connection to localhost instead of Twilio.
- The application should be overwriting it and it’s not being overwritten.

**To Reproduce**
1. The saving is occasionally defaulting back to the example.com/3000.
2. Add your Twilio Credentials
3. Send your messages
4. See the error logs in Twilio
5. You should see an error 112000 HTTP retrieval failure
6. Within it, you will find a url looking like this: example.com/3000

**Comment by Arique1104** [comment]
Some of the services, it's not taking all the characteristics from the Twilio messaging service.

example url needs to shift.  It's old code that.

In the description of the error message url, example.com/3000 << default variables in env config file.  When they are saving the Twilio it should replace it to Twilio's callback url.

**Comment by mau11** [comment]
This is an issue with the .env file defaults.
