### ISSUE TITLE
Bug: Upload Contacts not opening file picker 

### ISSUE THREAD

**Issue by markyv18** [StateVoicesNational/Spoke#2225]
**Describe the bug**
When building a campaign, the ability to upload a CSV is not working.  Click the button, nothing happens. 

**To Reproduce**
1. Go to the "+" button and create a new campaign
2. Click on 'contacts'
3. Click on 'upload contacts'
4. See error (no error visible, just that the file selector does not pop up)

**Expected behavior**
Would expect a finder file window (macOS) to appear and allow for the desired CSV to be chosen and opened. 

**Screenshots**

**Platform (please complete the following information):**
 - OS: macOS 12.4 and 12.6
 - Browser safari and chrome on both OS's
 - Desktop (owner's portal) 
 - Version:  latest version?  We pulled down a week ago.  Thanks!! 

**Additional context**

**Comment by markyv18** [comment]
Had this happen again and it seems it's a JS flaw possibly on my end?  If i simply refresh the page, no luck. If i close out chrome and restart... still doesnt fix it but if i restart the computer... it will work.  Go figure.

**Comment by mau11** [comment]
Thank you @markyv18, this issue has been resolved and does not occur in Spoke v14
