### ISSUE TITLE
Bug: SQLite incompatibility

### ISSUE THREAD

**Issue by crayolakat** [StateVoicesNational/Spoke#2234]
**Describe the bug**
SQLite is the default database engine for Spoke development environments, but is not compatible with Spoke.

**To Reproduce**
1. Follow the instructions [here](https://moveonorg.github.io/Spoke/#/HOWTO_DEVELOPMENT_LOCAL_SETUP) to set up your development environment. Use the default SQLite as your database engine- don't set up Postgres or Docker.
2. Create an organization and campaign
3. Set up some fake contacts in the campaign and assign all of them to yourself
4. Switch to Texter mode and send some of the texts, but not all
5. Go back to Admin mode and click the campaign you just created
6. Next to your texter's name, click the "Unmessaged" hyperlink
7. **Issue:** There is a GraphQL error. The Spoke terminal describes the following errors: `Query cancelling not supported for this dialect` and `value is not an instance of Date`

**Expected behavior**
SQLite should either be made compatible with Spoke, or removed as the default database engine and Spoke should stop supporting it.

**Screenshots**
![image](https://user-images.githubusercontent.com/9382984/199112318-e61d2fca-a9db-4a8e-859e-fb414b952eaf.png)
![Screen Shot 2022-10-31 at 2 17 47 PM](https://user-images.githubusercontent.com/9382984/199112598-39ad1350-3702-4bd7-a129-e648963533b8.png)

**Platform:**
 - OS: MacOS
 - Browser: Chrome
 - Desktop
 - Version: 106.0.5249.119

**Additional context**
I didn't search for more SQLite errors after encountering the described errors above. There may be more.

**Comment by engelhartrueben** [comment]
Issue still persists into Spoke v14.0 - adding to To-Do list
