### ISSUE TITLE
Bug: Bulk send not working

### ISSUE THREAD

**Issue by poketama** [StateVoicesNational/Spoke#2237]
**Describe the bug**
When bulk send is enabled, the green box with 'Send 50' shows up. When clicked the app hangs and does nothing.

**Expected behavior**
Send all the text messages. Outside of the US this is not a legal requirement and would save a fair bit of time.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows and Mac
 - Browser: Chrome latest 
 - Desktop or Mobile: Desktop
 - Version [e.g. 22]: Unable to find this info

**Comment by michael-gratton** [comment]
Hi @poketama , which version of Spoke do you have installed? A number of issues with bulk send were fixed in 12.1.
