### ISSUE TITLE
Feature Request: Option to display phone number under textee name

### ISSUE THREAD

**Issue by poketama** [StateVoicesNational/Spoke#2238]
**Problem**
When my organisation sends out texts we have to look up the person on NationBuilder to action the results.  Our current process is to use a canned response which displays the persons name and phone number, this is super clunky and takes more time. 

I often get halfway through writing a message, then have to use the canned response, so I will copy the half-written message, paste it in my address bar to hold it, open the canned response, copy the phone number, search it on NationBuilder, delete the canned response, and then copy my half-written message again and paste it in the response field. This sounds absurd, but its genuinely the fastest way I've found to work at the moment.

**Solution**
We could speed this up a lot by having the phone number readily visible (and maybe even with the ability to click it to copy it to the clipboard).

**Comment by mau11** [comment]
Thank you @poketama for sharing this request. Displaying phone numbers to volunteers raises privacy concerns.
