### ISSUE TITLE
Feature Request: Delete readmestaging20180902 file

### ISSUE THREAD

**Issue by crayolakat** [StateVoicesNational/Spoke#2241]
**Problem**
Unused and unneeded file named [readmestaging20180902](https://github.com/MoveOnOrg/Spoke/blob/2e8c479ef7e4071bc903bdf882334488b50f2910/readmestaging20180902) exists in repo

**Solution**
Delete the readmestaging20180902 file

**Context**
<img width="1440" alt="Screenshot 2022-11-28 at 9 53 05 PM" src="https://user-images.githubusercontent.com/9382984/204449863-7ce7cd59-dd6b-40da-a93a-4b9a02fcddac.png">

**Comment by SshibamDebnathh** [comment]
hey I 'll get the job done!

**Comment by crayolakat** [comment]
@shivphp Thanks! Can you create a pull request?

**Comment by SshibamDebnathh** [comment]
I have created  a pull request , thanks
