### ISSUE TITLE
Issue with one-click deploy in Heroku now that hobby-dev plan is not available

### ISSUE THREAD

**Issue by michael-poland** [StateVoicesNational/Spoke#2245]
**Describe the bug**
Both the production and sandbox one click deploy options from GitHub are currently not working since 1 December when Heroku ended the use of hobby-dev plans.

**To Reproduce**
1. Go to use one-click deploy
2. Click on either production or sandbox deploy links in MoveOnOrg/Spoke on GitHub
3. Complete details in Heroku, click deploy
4. See error:

For production just "The heroku-redis:hobby-dev plan is no longer available. Choose a different plan." and for sandbox both The heroku-postgresql:hobby-dev plan is no longer available. Choose a different plan" and "The heroku-redis:hobby-dev plan is no longer available. Choose a different plan."

A block to deployment as app needs to be deployed to select a different plan. 

**Expected behavior**
Smooth deployment as per in the past when hobby-dev plans were available 

**Screenshots**
![Screen Shot 2022-12-08 at 11 49 02](https://user-images.githubusercontent.com/120068809/206329099-91330164-6cb7-4ef2-b295-7978b94cb31b.png)

**Platform (please complete the following information):**
 - macOS Monterey
 - Safari
 - Desktop
 - Version  15.6.1

**Additional context**

**Comment by HorseJump** [comment]
I created this pull request that should fix it here: https://github.com/MoveOnOrg/Spoke/pull/2254

**Comment by mau11** [comment]
Hi @michael-poland, this has been fixed: https://github.com/StateVoicesNational/Spoke/pull/2254
