### ISSUE TITLE
Bug: Dockerfile node version doesn't match minimum requirement

### ISSUE THREAD

**Issue by johntwyman** [StateVoicesNational/Spoke#2265]
**Describe the bug**
The Dockerfile in the code base references node version 12. The minimum version required now is version 16. As such, any image built from this Dockerfile fails to start.

**To Reproduce**
1. `docker build . -t spoke-v13`
2. `docker run spoke-v13`
3. View logs, see error

**Expected behavior**

**Platform (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - Desktop or Mobile: N/A
 - Version: 13.0

**Comment by openbrian** [comment]
I also see this issue.
