### ISSUE TITLE
UI Visual Updates: Admin UI Language & Workflow

### ISSUE THREAD

**Issue by Arique1104** [StateVoicesNational/Spoke#2271]
- The add-campaign "+" button
- The “___” for text messages
- Language Update

**Comment by mau11** [comment]
Closed as this is a duplication of issues:
https://github.com/StateVoicesNational/Spoke/issues/2272
https://github.com/StateVoicesNational/Spoke/issues/2275
https://github.com/StateVoicesNational/Spoke/issues/2270
