### ISSUE TITLE
Bug: Twilio Deprecating Node16

### ISSUE THREAD

**Issue by Arique1104** [StateVoicesNational/Spoke#2311]
**Describe the bug**
February 2024 is Twilio's deadline to upgrade out of Node16.  At the time of this report, there is a node version 21, but we are prioritizing going to node version 18 to give us more breathing room.

**To Reproduce**
1. Have a Twilio Integration with Spoke

**Expected behavior**
Expect Spoke to function.  Come February 2024, Twilio will force the application to run on Node18 or higher .

**Platform (please complete the following information):**
 - Desktop or Mobile?

**Additional context**

**Comment by engelhartrueben** [comment]
fixed in 14.0
